### PR TITLE
Move thunderstorm icon to the “rain diagram” and scale the icon according to the risk of thunderstorm

### PR DESCRIPTION
**Pull request by julienrf**
image

Credits to @Boran for the idea.

### CODE REVIEW

**Comment by julienrf** [comment]
One thing that I am not super happy with is that it looks like the thunderstorm risk is always in the middle of the day (because of the way we center it in the diagram), although when we compute it we take into account the data for the entire day.

**Comment by Boran** [comment]
Good point.

**Comment by Boran** [comment]
Yes, much better anyway, commit?
Or add a note to the help page too? :-)

**Comment by julienrf** [comment]
Some last changes:

image


And a sentence about it in the help:

image

**Pull request merged**
