### PR TITLE
Show cumulus clouds

### PR DESCRIPTION
**Pull request by julienrf**
One thing that I find useful in the current soaringmeteo is the indication of cumulus clouds:

Screenshot from 2023-03-05 21-25-10

Screenshot from 2023-03-05 21-27-31

We immediately see whenever there will be nice cumulus clouds, or if there is a risk of overdevelopment.

In soarV2, I wanted to show all the clouds in the meteograms (not just cumulus clouds), a bit like what meteoblue does:

Screenshot 2023-03-05 at 21-28-56 Météogramme Lecco - meteoblue

As a result, there is no super clear indication of the presence of cumulus clouds. for instance:

Screenshot 2023-03-05 at 21-33-54 SoaringMeteo

Users have to learn that whenever there are some clouds indicated around the top of the boundary layer, probably it means cumulus clouds.

I took some time to experiment and see if we could show the presence of cumulus clouds more clearly. The result looks like this:

Screenshot 2023-03-05 at 21-35-58 SoaringMeteo

Also in sounding diagrams:

Screenshot 2023-03-05 at 21-23-35 SoaringMeteo

However, I feel a bit stuck. I don’t think I like better the change. The mix of cumulus clouds with other types of clouds does not look very well.

Also, the clouds cover as shown in the meteograms and soundings diagrams directly comes from the output of the GFS model, whereas the cloud base and cloud size is computed on our size and the formula is pretty approximate (especially for the cloud size). Actual models of clouds (as I guess are used in GFS) are much more sophisticated than that, which leads me to think that it’s probably better to not show our cumulus clouds and simply let the users guess that there are some cumulus clouds because there is some cloud cover shown around the top of the boundary layer.

Do you have an opinion?

Here are some other screenshots:

Screenshot 2023-03-05 at 21-22-59 SoaringMeteo
Screenshot 2023-03-05 at 21-23-15 SoaringMeteo
Screenshot 2023-03-05 at 21-23-23 SoaringMeteo

### CODE REVIEW

**Comment by Boran** [comment]
Yes it would be useful, but as you say it affects the readability/clarity.
How about a separate horizontal section, like gfs.
Or just outline the clouds, perhaps in a colour (without the white fill)?
When the "clouds" are very vertical they do nit look like clouds any more..

Or. Instead of an extendable cloud drawing, a fixed size image, that i copied every 300m (for example) vertically?

**Comment by julienrf** [comment]
Alright, I went with a different approach. Instead of showing an image that looks like a cumulus cloud, I show a “box” that delimits the height of the clouds. I was a bit inspired by the Meteoblue sounding diagrams that show the cloud bottom and top with two lines:

Screenshot 2023-04-01 at 20-10-19 Stueve   Sounding Lausanne - meteoblue

In our sounding diagrams, the height and size of the cumulus clouds are now shown with a box:

Screenshot 2023-04-01 at 19-57-27 SoaringMeteo

The bottom of the dotted white box shows the cloud base, and the top of the box shows the cloud top. I like how it also highlights in the sounding diagram the area where the air temperature is close to the dew point temperature. I agree that the box is not self-explanatory, so I have explained how to read it in the help:

Screenshot 2023-04-01 at 19-58-21 SoaringMeteo

We also write the altitude of cloud base in the sounding diagram, since that’s a useful information.

Here are a couple of other examples:

Screenshot 2023-04-01 at 19-57-45 SoaringMeteo

Screenshot 2023-04-01 at 19-58-13 SoaringMeteo

And a comparison with the current state of soarV2. Before:

Screenshot 2023-04-01 at 20-08-06 SoaringMeteo

After:

Screenshot 2023-04-01 at 20-08-20 SoaringMeteo

In meteograms, the dotted white boxes don’t have the “overlapping issue” with the cloud cover that I mentioned in a previous post:

Screenshot 2023-04-01 at 19-58-32 SoaringMeteo

Screenshot 2023-04-01 at 19-59-06 SoaringMeteo

Screenshot 2023-04-01 at 19-58-47 SoaringMeteo

Comparison with the current soarV2. Before:

Screenshot 2023-04-01 at 20-08-34 SoaringMeteo

After:

Screenshot 2023-04-01 at 20-08-39 SoaringMeteo

**Comment by Boran** [comment]
Interesting
In this image, what is the grey square at 3500m, clouds that are not cumulus?
image
Should the grey squares not disappear?

**Comment by julienrf** [comment]
The thing is that we have two sources of information. 1) The output of GFS provides the cloud cover at various altitudes (shown by the white/gray areas). 2) We compute our own estimate of the cumulus clouds base and size.
I would like to show both information on the meteogramme because they don't really overlap. So, in your screenshot, the gray area comes from the output of GFS.

**Comment by julienrf** [comment]
After another look at the formula used to compute the clouds top, I am not convinced this formula is correct, so I’d rather show only the cloud base for now (which is a very useful information, IMHO because it tells you whether it is likely to get cumulus clouds vs blue thermals).

image

image


image

image

**Comment by Boran** [comment]
Yes, the single dotted line is easier to read.

But I still preferred the initial puffy cloud:
image

Even if extending the height was not doable.

**Comment by julienrf** [comment]
We could show a puffy cloud extending from the cloud base to the top of the boundary layer. However, I wonder if it would “conflict” visually with the cloud cover information shown in the meteograms. I can give it a try, though…

**Comment by julienrf** [comment]
Here is a variation with the puffy clouds (I limited the height to the boundary layer top):

image

image


image

**Comment by Boran** [comment]
Personally I find that much better. @flav-allaz : What do you think?

**Comment by flav-allaz** [comment]
+1 for the «puffy» clouds. A further idea would be to darkened the cloud depending on its size (like the GFS icon).

Have you tried to switch the background from blue to white or very light blue? For me it's very disturbing that the "blue sky" background can be darker than some types of GFS clouds.

**Comment by Boran** [comment]
Very good. Thanks.

**Pull request closed without merging**
