### PR TITLE
Add day overview to the location summary for WRF

### PR DESCRIPTION
**Pull request by julienrf**
Before:

Screenshot 2024-01-04 at 18-04-05 SoaringMeteo

After:

Screenshot 2024-01-04 at 18-01-25 SoaringMeteo

### CODE REVIEW

**Comment by julienrf** [comment]
Deployed on https://soarwrf3.soaringmeteo.org/v2

**Comment by Boran** [comment]
Nice. Merci.

**Comment by Boran** [comment]
Hmm. How about a 3-4 day "week" overview  too, with a colored box for each day at 13h, fir example?

**Comment by julienrf** [comment]
The WRF model provides 2-days of forecast only. We could use the data from the GFS model, but tthat would require many changes in the UI implementation.

**Comment by Boran** [comment]
Ah, I thought we could have had 3 or 4 days, it was just a question of computing power.
Ok, drop this request.

**Comment by julienrf** [comment]
I believe we could have 3 days on the new server. Maybe 4, yes.

So yes, your suggestion is also a possibility. Let’s track it in #116

**Pull request merged**
