### PR TITLE
Update a “marker file” when we are done writing the forecast results

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by Boran** [comment]
You could also put a date/time into the file too?

**Comment by julienrf** [comment]
You can get the date with `stat -c %Y v2/data/marker`. Is that enough?

**Comment by Boran** [comment]
Yes, but the file could also be read remotely via http?

**Comment by julienrf** [comment]
Ah, I think I see what you mean. In that case, I would suggest directly reading the file `forecast.json`:

~~~ sh
curl -s https://soarwrf1.soaringmeteo.org/v2/data/5/wrf/forecast.json | jq -r .init
curl -s https://soarwrf1.soaringmeteo.org/v2/data/5/gfs/forecast.json | jq -r .init
~~~

**Pull request merged**
