### PR TITLE
Set up internationalization infrastructure and update dependencies along the way

### PR DESCRIPTION
**Pull request by julienrf**
- Update our internal dependencies
- Set up an internationalization infrastructure based on the inlang stack
- Add French translation
- Document how to contribute translations
- Rename back “XC flying potential” to “thermal quality”
- Fix a couple of memory leak issues

### CODE REVIEW

**Comment by julienrf** [comment]
Deployed on https://soarwrf1.soaringmeteo.org/v2, here is a screencast:

[Screencast from 20-02-2024 17:56:23.webm](https://github.com/soaringmeteo/soaringmeteo/assets/332812/6ddac05e-b861-4e4f-84ce-d29dea8152da)

**Comment by julienrf** [comment]
The messages are loaded on-demand depending on the user selected language.

Currently, loading the website requires downloading 5 JavaScript files totaling 494 kB (162 kB compressed).

With this change, loading the website requires downloading 6 JavaScript files totaling 519 kB (172 kB compressed). Each language file weighs about 20 kB (7 kB compressed).

**Comment by Boran** [comment]
Excellent,  I looked at the Screencast, the doc in the pull request. I cannot really say much about the code,  looks clean 

One thing,  is the default English,  or could it be inherited from the browser? People who have a French navigator probably want the site in FR.

When it is merged. I cam add a text or too in German,  and ask some of out German speaking donors to contribute?

**Comment by julienrf** [comment]
> One thing, is the default English, or could it be inherited from the browser? People who have a French navigator probably want the site in FR.

When I looked at that a couple of weeks ago I thought it was a bit complicated and unreliable to auto-detect the user's preferred language, but I had another look this morning and I think something is doable, I will give it a try!

**Comment by julienrf** [comment]
I updated the PR based on your feedback: the menu option names in French are not capitalized anymore, and we detect the user lang based on their browser configuration. I’ve redeployed it on soarwrf1.

Screenshot 2024-02-22 at 14-33-23 SoaringMeteo

**Pull request merged**
